### ISSUE TITLE
Issue managing IPAM address that also has a DNS record associated with it

### ISSUE THREAD

**Issue by mra-cfs** [infobloxopen/terraform-provider-bloxone#144]
When I try to register an IPAM address to an IP that also has an existing A record I get this error;

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.this.bloxone_ipam_address.address["foo_eth0"], provider
│ "provider[\"registry.terraform.io/infobloxopen/bloxone\"]" produced an
│ unexpected new value: .comment: was cty.StringVal(""), but now
│ cty.StringVal("foo-eth0").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

I do have the resource "bloxone_ipam_address" "address" set to ;

```
  lifecycle {
    ignore_changes = [
      names
    ]
  }
```
  
but even with that in place I still get a tainted resource. It seems like it should be possible to set IPAM and DNS information on a given IP.

**Comment by unasra** [comment]
@mra-cfs Could you post a detailed configuration leading to this particular error ?

**Comment by unasra** [comment]
Due to no further updates , I will be locking this issue for now. Please feel free to create a new issue if the problem persists.
