### ISSUE TITLE
data.bloxone_dns_views.example_by_attribute.id is not available

### ISSUE THREAD

**Issue by SamirT-hub** [infobloxopen/terraform-provider-bloxone#69]
Hello, Once we have created the dns view via terraform we want to create authorative zone to this dns view. The only way to do it is to mention the view with the DNS view id (dns/views/XXXXXXX) and this is a very unique ID which reset once you recreated the dns view. What we want to do is to not have any dependencies to the ID so not fix it but rather get it back from the data source:
data "bloxone_dns_views" "example_by_attribute" {
  filters = {
    "name" = "example_view"
  }
}
Unfortunately the data.bloxone_dns_views.example_by_attribute.id doesn't get the id :/ ... Please could you help us on this subject ?

Many thanks.

**Comment by SamirT-hub** [comment]
view     = data.bloxone_dns_views.azprd.results.id
│
│ Can't access attributes on a list of objects. Did you mean to access attribute "id" for a specific element of the list, or across all elements of the list?

│ Error: Unsupported attribute
│
│   on azure.tf line 11, in module "iac--bloxone-authzoneazure":
│   11:   view     = data.bloxone_dns_views.azprd.id
│
│ This object has no argument, nested block, or exported attribute named "id".

**Comment by venkat-iblox** [comment]
@SamirT-hub data source typically returns an array of objects. In your example, you should be doing this instead to get the id
 ```
 view = data.bloxone_dns_views.azprd.results.0.id
 ```

**Comment by SamirT-hub** [comment]
Yes after some time using the output we found also this possibility data.bloxone_dns_views.azprd.results.*.id[0] :). Thank you !
