### ISSUE TITLE
bloxone_dns_forward_zone (Resource) fqdn (String) Server FQDN required for external_forwarders

### ISSUE THREAD

**Issue by SamirT-hub** [infobloxopen/terraform-provider-bloxone#75]
Hello,

Again me :), the fqdn is mandatory "Inappropriate value for attribute "external_forwarders": map has no element for required attribute "fqdn"." 

I don't understand why is it necessary the address ip only is enough normally no need for the fqdn server, in web ui for example we wan create a forward server group without mentionning any fqdn only ip address.

Is it possible to make it facultative please or have the entry of the fqdn which is equivalent to nothing ?

Thank you.

Samir TENNAH.

**Comment by SamirT-hub** [comment]
this means that now no need to add fqdn ? because I still have the issue:
"Inappropriate value for attribute "external_forwarders": map has no element for required attribute "fqdn"."

Thank you.

Samir TENNAH.

**Comment by SamirT-hub** [comment]
FYI, I am using csp.eu.infoblox.com as CSP.

Samir TENNAH.

**Comment by mathewab** [comment]
Yes, this issue is fixed and should be available in the next released version of the provider.

**Comment by SamirT-hub** [comment]
Thank you for this information when will be the next release please ?

Samir TENNAH.

**Comment by mathewab** [comment]
We released [v1.0.0](https://registry.terraform.io/providers/infobloxopen/bloxone/1.0.0) today. Please let us know if the issue has been resolved for you.
